INSERT INTO word_lists (id, title) VALUES
  ('action', 'Action Movies'),
  ('scifi', 'Sci-Fi Movies'),
  ('hp', 'Harry Potter'),
  ('got', 'Game of Thrones');

INSERT INTO words (id, list_id, word, hint) VALUES
  -- Action Movies (movie titles)
  ('a01', 'action', 'Die Hard', '🎄🔫🏢'),
  ('a02', 'action', 'Mad Max Fury Road', '🚗💨🏜️'),
  ('a03', 'action', 'The Matrix', '💊🕶️🟢'),
  ('a04', 'action', 'John Wick', '🐶🔫🖤'),
  ('a05', 'action', 'Terminator 2', '🤖🔫👦'),
  ('a06', 'action', 'The Dark Knight', '🦇🃏🌃'),
  ('a07', 'action', 'Gladiator', '⚔️🏟️👑'),
  ('a08', 'action', 'Kill Bill', '🗡️👘💛'),
  ('a09', 'action', 'Mission Impossible', '🎭💣🚁'),
  ('a10', 'action', 'The Bourne Identity', '🧠🔫🇪🇺'),
  ('a11', 'action', 'Speed', '🚌💣⏱️'),
  ('a12', 'action', 'Top Gun', '✈️😎🕶️'),
  ('a13', 'action', 'Raiders of the Lost Ark', '🎩🐍📦'),
  ('a14', 'action', 'Jurassic Park', '🦕🦖🏝️'),
  ('a15', 'action', 'The Transporter', '🚗📦🕴️'),
  ('a16', 'action', 'Taken', '📞👧🔫'),
  ('a17', 'action', 'Casino Royale', '🃏🍸🔫'),
  ('a18', 'action', 'Skyfall', '🇬🇧🔫🏚️'),
  ('a19', 'action', 'Inception', '🌀💤🏙️'),
  ('a20', 'action', 'The Raid', '🏢👊🇮🇩'),
  ('a21', 'action', 'Crouching Tiger Hidden Dragon', '🗡️🏯🍃'),
  ('a22', 'action', 'Oldboy', '🔨📦🐙'),
  ('a23', 'action', 'Leon The Professional', '🌱🔫👧'),
  ('a24', 'action', 'Heat', '🏦🔫☕'),
  ('a25', 'action', 'Point Break', '🏄👮🏦'),
  ('a26', 'action', 'Face Off', '🎭🔄🔫'),
  ('a27', 'action', 'True Lies', '💍✈️💃'),
  ('a28', 'action', 'Predator', '👽🌳🔫'),
  ('a29', 'action', 'Aliens', '👾👩🔫'),
  ('a30', 'action', 'RoboCop', '🤖👮🏙️'),
  ('a31', 'action', 'The Equalizer', '📚👊🚇'),
  ('a32', 'action', 'Atomic Blonde', '💇💄🔫'),
  ('a33', 'action', 'Nobody', '😠🚌👊'),
  ('a34', 'action', 'Extraction', '🚁👦🇮🇳'),
  ('a35', 'action', 'The Night Comes for Us', '🇮🇩🩸⚔️'),
  ('a36', 'action', 'Fury', '🪖🔥💥'),
  ('a37', 'action', 'Black Hawk Down', '🚁🏜️🔥'),
  ('a38', 'action', 'Saving Private Ryan', '🏖️🪖🇺🇸'),
  ('a39', 'action', '300', '🛡️⚔️🩸'),
  ('a40', 'action', 'Braveheart', '💙⚔️🏴󠁧󠁢󠁳󠁣󠁴󠁿'),
  ('a41', 'action', 'The Rock', '🏝️🧪🔓'),
  ('a42', 'action', 'Con Air', '✈️🔒🦜'),
  ('a43', 'action', 'Gone in 60 Seconds', '🚗⏱️🔑'),
  ('a44', 'action', 'Fast and Furious', '🚗👨‍👩‍👧‍👦💨'),
  ('a45', 'action', 'Baby Driver', '👶🚗🎵'),
  ('a46', 'action', 'Drive', '🚗🦂🤫'),
  ('a47', 'action', 'Bullet Train', '🚅🐍🍊'),
  ('a48', 'action', 'Everything Everywhere All at Once', '🥯🥋👵'),
  ('a49', 'action', 'The Batman', '🦇🕵️🌧️'),
  ('a50', 'action', 'Dune', '🏜️🐛👁️'),
  ('a51', 'action', 'Furiosa', '🚗🏜️👧'),
  ('a52', 'action', 'Mission Impossible Fallout', '🚁🪂💣'),

  -- Sci-Fi Movies (movie titles)
  ('s01', 'scifi', 'Blade Runner', '🌧️🤖🏙️'),
  ('s02', 'scifi', 'Blade Runner 2049', '🐝🤖💛'),
  ('s03', 'scifi', 'Star Wars A New Hope', '⭐⚔️🤖'),
  ('s04', 'scifi', 'The Empire Strikes Back', '❄️👨‍👦🖤'),
  ('s05', 'scifi', 'Return of the Jedi', '🐻⚔️👑'),
  ('s06', 'scifi', 'Interstellar', '🚀🌽⏳'),
  ('s07', 'scifi', '2001 A Space Odyssey', '⬛🐵💻'),
  ('s08', 'scifi', 'Arrival', '👽⭕️🗣️'),
  ('s09', 'scifi', 'Ex Machina', '🤖💃🔍'),
  ('s10', 'scifi', 'Her', '💌📱❤️'),
  ('s11', 'scifi', 'The Martian', '🥔🚀🔴'),
  ('s12', 'scifi', 'Gravity', '👩🚀🌌'),
  ('s13', 'scifi', 'District 9', '👽🦐🇿🇦'),
  ('s14', 'scifi', 'Children of Men', '👶🌍🔫'),
  ('s15', 'scifi', 'Minority Report', '👁️🔮👮'),
  ('s16', 'scifi', 'Total Recall', '🧠🔴💊'),
  ('s17', 'scifi', 'The Fifth Element', '🚕🧡👽'),
  ('s18', 'scifi', 'Back to the Future', '⏰🚗⚡'),
  ('s19', 'scifi', 'E.T. the Extra-Terrestrial', '👽🚲🌙'),
  ('s20', 'scifi', 'Close Encounters of the Third Kind', '🏔️🎵👽'),
  ('s21', 'scifi', 'Alien', '🚀🐱👾'),
  ('s22', 'scifi', 'Prometheus', '🧬🚀🗿'),
  ('s23', 'scifi', 'The Thing', '❄️🐕👾'),
  ('s24', 'scifi', 'They Live', '🕶️👽📡'),
  ('s25', 'scifi', 'Stalker', '🚂🌿🚪'),
  ('s26', 'scifi', 'Solaris', '🌊🧠🚀'),
  ('s27', 'scifi', 'Moon', '🌙🤖👤'),
  ('s28', 'scifi', 'Primer', '⏱️📦🔁'),
  ('s29', 'scifi', 'Coherence', '☄️🍷🔀'),
  ('s30', 'scifi', 'Annihilation', '🌈🐻🧬'),
  ('s31', 'scifi', 'Under the Skin', '👩👽🏍️'),
  ('s32', 'scifi', 'Edge of Tomorrow', '⏱️🔁👽'),
  ('s33', 'scifi', 'Looper', '🔫⏰👶'),
  ('s34', 'scifi', 'Source Code', '🚆💥🧠'),
  ('s35', 'scifi', 'Donnie Darko', '🐰✈️🌀'),
  ('s36', 'scifi', 'The Prestige', '🎩⚡🐦'),
  ('s37', 'scifi', 'Eternal Sunshine of the Spotless Mind', '🧠❄️💔'),
  ('s38', 'scifi', 'Gattaca', '🧬🏊🚀'),
  ('s39', 'scifi', 'Contact', '📡👩👽'),
  ('s40', 'scifi', 'War of the Worlds', '👽🗼🔥'),
  ('s41', 'scifi', 'Independence Day', '🇺🇸🛸💥'),
  ('s42', 'scifi', 'Men in Black', '🕶️👽🧠'),
  ('s43', 'scifi', 'Guardians of the Galaxy', '🦝🌳🎵'),
  ('s44', 'scifi', 'Avatar', '🔵🌳🐉'),
  ('s45', 'scifi', 'The Matrix Reloaded', '🛣️⚔️💊'),
  ('s46', 'scifi', 'Tron Legacy', '💿🔵🏍️'),
  ('s47', 'scifi', 'Ready Player One', '🎮🕹️🏁'),
  ('s48', 'scifi', 'Dune Part Two', '🪱🏜️⚔️'),
  ('s49', 'scifi', 'Star Trek', '🖖🚀🌌'),
  ('s50', 'scifi', 'The Day the Earth Stood Still', '👽🤖🌍'),
  ('s51', 'scifi', 'Pacific Rim', '🤖🌊👹'),
  ('s52', 'scifi', 'Oblivion', '🏚️🤖📚'),

  -- Harry Potter (lore mix)
  ('h01', 'hp', 'Harry Potter', '⚡👓🧙'),
  ('h02', 'hp', 'Hermione Granger', '📚🦷🪄'),
  ('h03', 'hp', 'Ron Weasley', '🧡🐭♟️'),
  ('h04', 'hp', 'Albus Dumbledore', '🧙‍♂️🍋🔥'),
  ('h05', 'hp', 'Severus Snape', '🖤🧪🦌'),
  ('h06', 'hp', 'Lord Voldemort', '👃🐍💀'),
  ('h07', 'hp', 'Rubeus Hagrid', '🧔🐉☂️'),
  ('h08', 'hp', 'Draco Malfoy', '👱🐍🟢'),
  ('h09', 'hp', 'Sirius Black', '🐶⭐🖤'),
  ('h10', 'hp', 'Remus Lupin', '🌕🐺🍫'),
  ('h11', 'hp', 'Minerva McGonagall', '🐱📗🪄'),
  ('h12', 'hp', 'Riddle Diary', '📓🖋️🐍'),
  ('h13', 'hp', 'Horcrux', '💎🐍📖'),
  ('h14', 'hp', 'Elder Wand', '🪄🌳💀'),
  ('h15', 'hp', 'Invisibility Cloak', '👻🧥✨'),
  ('h16', 'hp', 'Resurrection Stone', '💍👻🔘'),
  ('h17', 'hp', 'Sorting Hat', '🎩🗣️🏠'),
  ('h18', 'hp', 'Hogwarts', '🏰🚂⭐'),
  ('h19', 'hp', 'Gryffindor', '🦁🔴🥇'),
  ('h20', 'hp', 'Slytherin', '🐍🟢🏆'),
  ('h21', 'hp', 'Hufflepuff', '🦡🟡☕'),
  ('h22', 'hp', 'Ravenclaw', '🦅🔵📚'),
  ('h23', 'hp', 'Quidditch', '🧹⚽💍'),
  ('h24', 'hp', 'Golden Snitch', '🟡🪽⚡'),
  ('h25', 'hp', 'Platform Nine and Three Quarters', '🧱🚂9️⃣'),
  ('h26', 'hp', 'Diagon Alley', '🛒🧙‍♂️🏦'),
  ('h27', 'hp', 'Gringotts', '🏦🐉⛏️'),
  ('h28', 'hp', 'Hedwig', '🦉✉️❄️'),
  ('h29', 'hp', 'Dobby', '🧦🧝🆓'),
  ('h30', 'hp', 'Kreacher', '🏠🧝🖤'),
  ('h31', 'hp', 'Fawkes', '🔥🐦💧'),
  ('h32', 'hp', 'Buckbeak', '🦅🐴⛰️'),
  ('h33', 'hp', 'Norbert', '🐉🥚🇳🇴'),
  ('h34', 'hp', 'The Basilisk', '🐍👁️💀'),
  ('h35', 'hp', 'Expecto Patronum', '🦌✨🛡️'),
  ('h36', 'hp', 'Avada Kedavra', '💚💀🪄'),
  ('h37', 'hp', 'Expelliarmus', '🪄✋💥'),
  ('h38', 'hp', 'Wingardium Leviosa', '🪶⬆️🪄'),
  ('h39', 'hp', 'Marauders Map', '🗺️👣✨'),
  ('h40', 'hp', 'Time Turner', '⏳🔁👧'),
  ('h41', 'hp', 'Mirror of Erised', '🪞💭❤️'),
  ('h42', 'hp', 'Philosopher Stone', '💎❤️♾️'),
  ('h43', 'hp', 'Triwizard Tournament', '🏆🐉🧜'),
  ('h44', 'hp', 'Goblet of Fire', '🏆🔥📜'),
  ('h45', 'hp', 'Deathly Hallows', '△⚪🪄'),
  ('h46', 'hp', 'Azakaban', '🏝️👻⛓️'),
  ('h47', 'hp', 'Dementor', '👻🥶💋'),
  ('h48', 'hp', 'Thestral', '🐴💀👀'),
  ('h49', 'hp', 'Nimbus 2000', '🧹💨2️⃣'),
  ('h50', 'hp', 'Firebolt', '🧹🔥⚡'),
  ('h51', 'hp', 'Room of Requirement', '🚪✨📦'),
  ('h52', 'hp', 'Chamber of Secrets', '🐍🚽🔑'),

  -- Game of Thrones (lore mix)
  ('g01', 'got', 'Jon Snow', '❄️🐺🗡️'),
  ('g02', 'got', 'Daenerys Targaryen', '🐉🔥👩'),
  ('g03', 'got', 'Tyrion Lannister', '🍷📚🦁'),
  ('g04', 'got', 'Arya Stark', '🗡️👁️🐺'),
  ('g05', 'got', 'Sansa Stark', '🐺👑❄️'),
  ('g06', 'got', 'Cersei Lannister', '🍷👑💣'),
  ('g07', 'got', 'Jaime Lannister', '🦁✋⚔️'),
  ('g08', 'got', 'Bran Stark', '🌳👁️🪑'),
  ('g09', 'got', 'Ned Stark', '🐺✂️❄️'),
  ('g10', 'got', 'The Night King', '🧊👑🧟'),
  ('g11', 'got', 'Khal Drogo', '🐎💪🔥'),
  ('g12', 'got', 'Jorah Mormont', '🐻🛡️💔'),
  ('g13', 'got', 'Samwell Tarly', '📚🐻🎓'),
  ('g14', 'got', 'Brienne of Tarth', '⚔️💙🛡️'),
  ('g15', 'got', 'Sandor Clegane', '🔥🐶🗡️'),
  ('g16', 'got', 'Gregor Clegane', '💀🏔️👊'),
  ('g17', 'got', 'Petyr Baelish', '🐦💰🗡️'),
  ('g18', 'got', 'Varys', '🕷️🗣️🥚'),
  ('g19', 'got', 'Melisandre', '🔴🔥👶'),
  ('g20', 'got', 'Stannis Baratheon', '🦌🔥⚔️'),
  ('g21', 'got', 'Robert Baratheon', '🍺🦌👑'),
  ('g22', 'got', 'Joffrey Baratheon', '👑🍷🤢'),
  ('g23', 'got', 'The Wall', '🧱❄️🧟'),
  ('g24', 'got', 'Winterfell', '🏰🐺❄️'),
  ('g25', 'got', 'Kings Landing', '🏙️🦁👑'),
  ('g26', 'got', 'Iron Throne', '⚔️💺👑'),
  ('g27', 'got', 'Valyrian Steel', '⚔️✨🐉'),
  ('g28', 'got', 'Dragonglass', '🖤🗡️🧟'),
  ('g29', 'got', 'Drogon', '🐉⬛🔥'),
  ('g30', 'got', 'Rhaegal', '🐉🟢🔥'),
  ('g31', 'got', 'Viserion', '🐉🟡🧊'),
  ('g32', 'got', 'Direwolf', '🐺❄️🌙'),
  ('g33', 'got', 'Ghost', '🐺⬜👁️'),
  ('g34', 'got', 'Nymeria', '🐺🏃‍♀️🗡️'),
  ('g35', 'got', 'White Walkers', '🧊🧟❄️'),
  ('g36', 'got', 'Wildfire', '💚🔥💥'),
  ('g37', 'got', 'Red Wedding', '💒🩸🗡️'),
  ('g38', 'got', 'Battle of the Bastards', '⚔️🐺🌨️'),
  ('g39', 'got', 'The Long Night', '🌙🧟🔥'),
  ('g40', 'got', 'House Stark', '🐺❄️📜'),
  ('g41', 'got', 'House Lannister', '🦁💰👂'),
  ('g42', 'got', 'House Targaryen', '🐉🔥🩸'),
  ('g43', 'got', 'House Baratheon', '🦌⚡👑'),
  ('g44', 'got', 'Night Watch', '⬛❄️🛡️'),
  ('g45', 'got', 'Faceless Men', '🎭🗡️🙏'),
  ('g46', 'got', 'Needle', '🗡️👧🐺'),
  ('g47', 'got', 'Longclaw', '⚔️🐺🐻'),
  ('g48', 'got', 'Ice', '⚔️❄️👨'),
  ('g49', 'got', 'Hodor', '🚪🧠💪'),
  ('g50', 'got', 'Three Eyed Raven', '🌳👁️🐦'),
  ('g51', 'got', 'Iron Bank', '🏦💰⚖️'),
  ('g52', 'got', 'Valar Morghulis', '💀🙏🎭');
